# Generated by Django 4.2.2 on 2023-06-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Phone', 'Phone'), ('TV', 'TV')], max_length=200),
        ),
    ]
