# Generated by Django 4.2.2 on 2023-06-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cart',
            field=models.ManyToManyField(blank=True, null=True, to='eshop.product'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_image',
            field=models.ImageField(null=True, upload_to='customer_images/'),
        ),
    ]
