# Generated by Django 4.2.2 on 2023-06-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0006_customer_cart_customer_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cart',
            field=models.ManyToManyField(null=True, to='eshop.product'),
        ),
    ]
