# Generated by Django 4.2.2 on 2023-06-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0015_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='eshop.cartitem'),
        ),
    ]
